name: Deploy Swaplings app 
on:
  push:
    branches: 
      - master
jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install node modules
        run: npm install

      - name: Build
        run: npm build