name: Deploy Swaplings app 
on:
  push:
    branches: 
      - main

jobs:
  deploy_client_to_vercel:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install node modules
        run: npm install

      - name: Build
        run: npm run build
      
      - name: Run tests
        run: npm run test

      - name: Deploy to Vercel production
        uses: amondnet/vercel-action@v20
        id: deploy-vercel-production
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          scope: ${{ secrets.VERCEL_ORG_ID }}


  deploy_server_to_heroku:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: server
    
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install node modules
        run: npm install

      - name: Build tsc
        run: tsc

      - name: Deploy to Heroku production
        uses: onekiloparsec/heroku-node-deploy-subfolder@v1.1.0
        with: 
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_branch: 'main'
          subfolder: 'server'

